version = 1
SPDX-PackageName = "dde-launchpad"
SPDX-PackageSupplier = "UnionTech Software Technology Co., Ltd.  <>"
SPDX-PackageDownloadLocation = "https://github.com/linuxdeepin/dde-launchpad"

[[annotations]]
path = ["debian/**", "rpm/**", "archlinux/**", ".packit.yaml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["misc/**.in", "cmake/**.cmake"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".github/**", ".obs/**", ".tx/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README.md", "README.**.md", "docs/**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**/icons/**.dci", "**/icons/**.svg", "**/texts/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["**.qrc", "**/qmldir"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/translations/**.ts"
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["**.deepin.dde.**.xml", "**/org.desktopspec.**.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["panels/dock/api/dbus/**.xml", "panels/dock/taskmanager/api/dbus/**.xml", "panels/dock/dockplugin/protocol/**.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "frame/layershell/protocol/wlr-layer-shell-unstable-v1.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Drew DeVault"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "panels/dock/taskmanager/api/wayland-protocols/treeland-foreign-toplevel-manager-v1.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.sh"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["misc/**.service", "misc/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "panels/dock/tray/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "toolGenerate/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
